[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
chrono ={ workspace = true }
bigdecimal = { workspace = true }
